language: node_js
sudo: false
os:
  - linux
  - windows
node_js:
  - '4'
  - '5'
  - '6'
  - 'stable'
script:
  - npm run lint
  - npm run test:typings
  - npm run test
cache:
  directories:
    - node_modules
